### ISSUE TITLE
Allow build on system without fonts

### ISSUE THREAD

**Issue by mtrakal** [usefulness/easylauncher-gradle-plugin#201]
I try to use version 4.0.0 with docker image without preinstalled fonts / font support in JDK.
In this case it's not possible to build app.

More info in: https://github.com/alvr/alpine-android/issues/12

It would be nice when EasyLauncher could use some bundled font if it's possible.

**Comment by mateuszkwiecinski** [comment]
Hey @mtrakal 👋

>It would be nice when EasyLauncher could use some bundled font if it's possible.

Version 4.0 actually comes with bundled [Roboto font](https://github.com/usefulness/easylauncher-gradle-plugin/blob/master/easylauncher/src/main/kotlin/com/project/starter/easylauncher/filter/DefaultFont.kt#L7) as a fallback, so it should work in an environment without preinstalled fonts. 

Matching your stacktrace with the source code the result points at a method responsible for [finding proper text size](https://github.com/usefulness/easylauncher-gradle-plugin/blob/master/easylauncher/src/main/kotlin/com/project/starter/easylauncher/filter/ChromeLikeFilter.kt#L96), which relies on having the a [font loaded](https://github.com/usefulness/easylauncher-gradle-plugin/blob/master/easylauncher/src/main/kotlin/com/project/starter/easylauncher/filter/ChromeLikeFilter.kt#L32-L35), but clearly in your setup loading the [default font](https://github.com/usefulness/easylauncher-gradle-plugin/blob/master/easylauncher/src/main/kotlin/com/project/starter/easylauncher/filter/DefaultFont.kt) also failed :/ 
I would guess it's enough to install `fontconfig` on a docker image, but as far as I can see you already did it and it didn't help 🤔 I won't have time to debug the issue this week, but I'll let you know as soon as I have any updates

**Comment by mtrakal** [comment]
Hi, it looks, that I provided wrong font name, when I now checking names for ttf-dejavu (I used: `font: "DejaVu"` but it looks should be `font: "DejaVu Sans"` or maybe `font: "DejaVuSans"`) so it looks as related to NPE that I provided name, but system didn't found font for this name.

```kotlin
GraphicsEnvironment.getLocalGraphicsEnvironment().availableFontFamilyNames.forEach {
    println(it)
}
```
output on my Windows machine
```
DejaVu Math TeX Gyre
DejaVu Sans
DejaVu Sans Condensed
DejaVu Sans Light
DejaVu Sans Mono
DejaVu Serif
DejaVu Serif Condensed
```


When I try this:
image: alvrme/alpine-android-liberica:android-30-jdk8
apk add --no-cache freetype fontconfig ttf-dejavu
and use it without dejavu font (but install fontconfig)

`filters = chromeLike(label: "staging")`
it failed on:
<details>
<summary>

```
Caused by: java.io.IOException: Problem reading font data.
	at com.project.starter.easylauncher.filter.DefaultFontKt$DEFAULT_EASYLAUNCHER_FONT$2.invoke(DefaultFont.kt:8)
	at com.project.starter.easylauncher.filter.DefaultFontKt$DEFAULT_EASYLAUNCHER_FONT$2.invoke(DefaultFont.kt:5)
```
</summary>

```
at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$run$1(DefaultBuildOperationExecutor.java:71)
	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.runWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:45)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:71)
	at org.gradle.initialization.BuildOperationFiringTaskExecutionPreparer.prepareForTaskExecution(BuildOperationFiringTaskExecutionPreparer.java:56)
	at org.gradle.initialization.DefaultGradleLauncher.prepareTaskExecution(DefaultGradleLauncher.java:233)
	at org.gradle.initialization.DefaultGradleLauncher.doClassicBuildStages(DefaultGradleLauncher.java:168)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
	at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:125)
	at org.gradle.internal.invocation.GradleBuildController$1.create(GradleBuildController.java:71)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:213)
	at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:67)
	at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:56)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:31)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:66)
	at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
	at org.gradle.tooling.internal.provider.FileSystemWatchingBuildActionRunner.run(FileSystemWatchingBuildActionRunner.java:90)
	at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:41)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:49)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:44)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:44)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.lambda$execute$0(InProcessBuildActionExecuter.java:59)
	at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:58)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
	at org.gradle.launcher.exec.BuildTreeScopeLifecycleBuildActionExecuter.lambda$execute$0(BuildTreeScopeLifecycleBuildActionExecuter.java:34)
	at org.gradle.internal.buildtree.BuildTreeState.run(BuildTreeState.java:53)
	at org.gradle.launcher.exec.BuildTreeScopeLifecycleBuildActionExecuter.execute(BuildTreeScopeLifecycleBuildActionExecuter.java:33)
	at org.gradle.launcher.exec.BuildTreeScopeLifecycleBuildActionExecuter.execute(BuildTreeScopeLifecycleBuildActionExecuter.java:28)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:104)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:55)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:64)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:37)
	at org.gradle.tooling.internal.provider.SessionScopeLifecycleBuildActionExecuter.lambda$execute$0(SessionScopeLifecycleBuildActionExecuter.java:54)
	at org.gradle.internal.session.BuildSessionState.run(BuildSessionState.java:67)
	at org.gradle.tooling.internal.provider.SessionScopeLifecycleBuildActionExecuter.execute(SessionScopeLifecycleBuildActionExecuter.java:50)
	at org.gradle.tooling.internal.provider.SessionScopeLifecycleBuildActionExecuter.execute(SessionScopeLifecycleBuildActionExecuter.java:36)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:58)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:42)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:47)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:31)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:65)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:29)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:84)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.io.IOException: Problem reading font data.
	at com.project.starter.easylauncher.filter.DefaultFontKt$DEFAULT_EASYLAUNCHER_FONT$2.invoke(DefaultFont.kt:8)
	at com.project.starter.easylauncher.filter.DefaultFontKt$DEFAULT_EASYLAUNCHER_FONT$2.invoke(DefaultFont.kt:5)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.project.starter.easylauncher.filter.DefaultFontKt.getDEFAULT_EASYLAUNCHER_FONT(DefaultFont.kt:5)
	at com.project.starter.easylauncher.filter.ChromeLikeFilter.<init>(ChromeLikeFilter.kt:35)
	at com.project.starter.easylauncher.plugin.EasyLauncherConfig.chromeLike(EasyLauncherConfig.kt:173)
	at com.project.starter.easylauncher.plugin.EasyLauncherConfig.chromeLike(EasyLauncherConfig.kt:213)
	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:484)
	at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:196)
	at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:98)
	at org.gradle.internal.extensibility.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:34)
	at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:56)
	at build_ecjpf23u0g1s7wa0ztc7ci11c$_run_closure3$_closure34$_closure37.doCall(/opt/atlassian/pipelines/agent/build/app/build.gradle:266)
	at org.gradle.util.ClosureBackedAction.execute(ClosureBackedAction.java:71)
	at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:154)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:105)
	at org.gradle.util.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:166)
	at org.gradle.api.internal.AbstractNamedDomainObjectContainer.create(AbstractNamedDomainObjectContainer.java:80)
	at org.gradle.api.internal.AbstractNamedDomainObjectContainer.create(AbstractNamedDomainObjectContainer.java:71)
	at org.gradle.api.internal.NamedDomainObjectContainerConfigureDelegate._configure(NamedDomainObjectContainerConfigureDelegate.java:39)
	at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:65)
	at build_ecjpf23u0g1s7wa0ztc7ci11c$_run_closure3$_closure34.doCall(/opt/atlassian/pipelines/agent/build/app/build.gradle:265)
	at org.gradle.util.ClosureBackedAction.execute(ClosureBackedAction.java:71)
	at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:154)
	at org.gradle.util.ConfigureUtil.configureSelf(ConfigureUtil.java:142)
	at org.gradle.api.internal.AbstractNamedDomainObjectContainer.configure(AbstractNamedDomainObjectContainer.java:91)
	at org.gradle.api.internal.AbstractNamedDomainObjectContainer.configure(AbstractNamedDomainObjectContainer.java:38)
	at org.gradle.internal.extensibility.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:53)
	at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:56)
	at build_ecjpf23u0g1s7wa0ztc7ci11c$_run_closure3.doCall(/opt/atlassian/pipelines/agent/build/app/build.gradle:264)
	at org.gradle.util.ClosureBackedAction.execute(ClosureBackedAction.java:71)
	at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:154)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:105)
	at org.gradle.util.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:166)
	at org.gradle.internal.extensibility.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:173)
	at org.gradle.internal.extensibility.ExtensionsStorage.configureExtension(ExtensionsStorage.java:64)
	at org.gradle.internal.extensibility.DefaultConvention.configureExtension(DefaultConvention.java:364)
	at org.gradle.internal.extensibility.DefaultConvention.access$500(DefaultConvention.java:45)
	at org.gradle.internal.extensibility.DefaultConvention$ExtensionsDynamicObject.tryInvokeMethod(DefaultConvention.java:301)
	at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:98)
	at org.gradle.internal.extensibility.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:34)
	at org.gradle.groovy.scripts.BasicScript$ScriptDynamicObject.tryInvokeMethod(BasicScript.java:135)
	at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:163)
	at org.gradle.groovy.scripts.BasicScript.invokeMethod(BasicScript.java:84)
	at build_ecjpf23u0g1s7wa0ztc7ci11c.run(/opt/atlassian/pipelines/agent/build/app/build.gradle:262)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
	... 154 more
```

</details>

**Comment by mateuszkwiecinski** [comment]
Hey @mtrakal 👋 
Could you provide a sample repository that fails with the same error? I tried to reproduce it locally without a success, so I created a [sample repository](https://github.com/mateuszkwiecinski/easylauncher_on_docker) with a simplest setup I understood should fail, but again, it produced valid artifacts: https://github.com/mateuszkwiecinski/easylauncher_on_docker/actions/runs/1153036551 👀 Did I miss something?

**Comment by headsvk** [comment]
Did you get this to run with JDK 11? I'm using `alvrme/alpine-android:android-30-jdk11-v2021.12.05` docker image.

I'm getting `java.lang.reflect.InvocationTargetException` even when just trying to print available fonts with `GraphicsEnvironment`.
I ran the apk command before running Gradle and it did install fonts so I'm not sure what is the problem.
```
12:15:43  [Pipeline] sh
12:15:43  + apk add --no-cache freetype fontconfig ttf-dejavu
12:15:43  fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
12:15:43  fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
12:15:43  (1/9) Installing libbz2 (1.0.8-r1)
12:15:43  (2/9) Installing libpng (1.6.37-r1)
12:15:43  (3/9) Installing freetype (2.10.4-r1)
12:15:43  (4/9) Installing libuuid (2.37.2-r0)
12:15:43  (5/9) Installing fontconfig (2.13.1-r4)
12:15:43  (6/9) Installing encodings (1.0.5-r0)
12:15:43  (7/9) Installing libfontenc (1.1.4-r0)
12:15:43  (8/9) Installing mkfontscale (1.2.1-r1)
12:15:43  (9/9) Installing ttf-dejavu (2.37-r1)
12:15:44  Executing busybox-1.33.1-r6.trigger
12:15:44  Executing fontconfig-2.13.1-r4.trigger
12:15:46  Executing mkfontscale-1.2.1-r1.trigger
12:15:46  OK: 44 MiB in 39 packages
...
12:15:46  [Pipeline] sh
12:15:47  + ./gradlew app:printAvailableFonts --stacktrace
...
12:18:49  > Task :app:printAvailableFonts FAILED
12:18:49  
12:18:49  FAILURE: Build failed with an exception.
12:18:49  
12:18:49  * What went wrong:
12:18:49  Execution failed for task ':app:printAvailableFonts'.
12:18:49  > java.lang.reflect.InvocationTargetException
...
12:18:49  Caused by: java.lang.reflect.InvocationTargetException
12:18:49  	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
12:18:49  	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
12:18:49  	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
12:18:49  	... 228 more
12:18:49  Caused by: java.lang.NullPointerException
12:18:49  	... 231 more
```

**Comment by mtrakal** [comment]
I run this in pipeline before run easylauncher: `- apk add --no-cache freetype fontconfig ttf-dejavu`

my easylauncher looks like:
```
debug {
            filters = customRibbon(font: "DejaVuSans", ribbonColor: "#99606060")
        }
```

**Comment by headsvk** [comment]
I have KTS build scripts and `file` is type of `File`, not just a string.
From Easylauncher code:
```
val fontName: String?
val font: File?
```

**Comment by mateuszkwiecinski** [comment]
Calling `customRibbon(font: "...")` passes the string as `fontName` - [source](https://github.com/usefulness/easylauncher-gradle-plugin/blob/master/easylauncher/src/main/kotlin/com/project/starter/easylauncher/plugin/EasyLauncherConfig.kt#L197) (and the reson why it works that way is when called from _Groovy_ the plugin receives arguments as `Map<String, Any>` so the type information is lost and I wanted to make the configuration as easy as possible )

If you're configuring the plugin from `kts` file then `customRibbon(fontName = "DejaVuSans")` should be equivalent of Groovy's `customRibbon(font: "DejaVuSans")`

**Comment by mtrakal** [comment]
Hmm, `image: alvrme/alpine-android:android-31-jdk11` crash on log below, but old version `image: alvrme/alpine-android:android-31-jdk11-v2021.08.01` works as expected. Looks like some changes in https://github.com/alvr/alpine-android caused this bug.
```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:easylauncherStagingRelease'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:145)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:143)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:131)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:402)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:389)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:382)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:368)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
Caused by: java.lang.InternalError: java.lang.reflect.InvocationTargetException
	at com.project.starter.easylauncher.filter.ChromeLikeFilter.getFont(ChromeLikeFilter.kt:105)
	at com.project.starter.easylauncher.filter.ChromeLikeFilter.apply(ChromeLikeFilter.kt:54)
	at com.project.starter.easylauncher.plugin.IconTransformerKt.transformImage(IconTransformer.kt:14)
	at com.project.starter.easylauncher.plugin.EasyLauncherTask.run(EasyLauncherTask.kt:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
	at org.gradle.api.internal.tasks.execution.TaskExecution$2.run(TaskExecution.java:239)

**Comment by RahulSDeshpande** [comment]
Guys if anyone is using CircleCI, then everything will work with `cimg/android:2022.06-node` Docker image.
💃🏼 💯

**Comment by StanglTobias** [comment]
Any news on this. I am using `image: alvrme/alpine-android:android-33-jdk11` and adding `apk add --no-cache freetype fontconfig ttf-dejavu` does not resolve the problem as suggested

**Comment by emartynov** [comment]
People, did you find a solution? I tried everything above and I'm getting 
```
Execution failed for task ':app:easylauncherDebug'.
> Fontconfig head is null, check your fonts or fonts configuration
```

I'm trying JSDK 21

**Comment by sarbyn** [comment]
Any update about this issue?
My setup is the following:

Docker image `ghcr.io/alvr/alpine-android:android-34-jdk17`

In my docker file there is the following line

`RUN apk add --no-cache freetype fontconfig ttf-dejavu`

The project config is the following
```
easylauncher {
    productFlavors {
        register("uat") {
            enable(true)
            filters(customRibbon(label = "UAT", fontName = "DejaVuSans", ribbonColor = "#6600CC"))
        }
        register("pre") {
            enable(true)
            filters(customRibbon(label = "PRE", fontName = "DejaVuSans",  ribbonColor = "#0000FF"))
        }
        register("pro") {
            enable(false)
        }
    }
}
````

But during the build, this error is thrown

```
 > Task :app:easylauncherPre**********Debug FAILED
 FAILURE: Build failed with an exception.
 * What went wrong:
 Execution failed for task ':app:easylauncherPre**********Debug'.
 > Couldn't load bundled font. Visit issue #201 for more details
```

**Comment by sarbyn** [comment]
There is no update for this issue, or a working alternative for modifing launcher icon?
