### ISSUE TITLE
Unsupported Webp Image

### ISSUE THREAD

**Issue by bruce3x** [usefulness/easylauncher-gradle-plugin#230]
run `./gradlew clean assembleRelease` then the build failed:

```
* What went wrong:
Execution failed for task ':app:easylauncherRelease'.
> Unsupported image format at /<project_path>/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp

...

Caused by: java.lang.IllegalStateException: Unsupported image format at /<project_path>/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
        at com.project.starter.easylauncher.plugin.IconTransformerKt.transformImage(IconTransformer.kt:13)
        at com.project.starter.easylauncher.plugin.EasyLauncherTask.run(EasyLauncherTask.kt:55)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        ...

```

jdk 11 + gradle 6.8.3

**Comment by bruce3x** [comment]
Sorry to reply so late.

Here is the webp image: [ic_launcher.webp.zip](https://github.com/usefulness/easylauncher-gradle-plugin/files/7466042/ic_launcher.webp.zip)

**Comment by mateuszkwiecinski** [comment]
Huh 🤔 I'm unable to reproduce the issue. I drafted https://github.com/usefulness/easylauncher-gradle-plugin/pull/231/files#diff-676d8586d383577429c50af926b8aa83c19bb31728e7f200a2f7313161fed756 which includes new test case of webp image you shared. Everything seems to be working in an expected way:

![image](https://user-images.githubusercontent.com/36954793/140054213-a2255998-0ed6-47fc-b28e-7eb30e421bd3.png)

Would you be able to modify the branch produce a failing test case?

**Comment by bruce3x** [comment]
🧐 Ok, I'll try to reproduce this issue this weekend.

**Comment by mateuszkwiecinski** [comment]
Closing due to inactivity 👀

**Comment by storytellerF** [comment]
No WEBPReaderSpi here.

<img width="602" alt="截屏2024-01-12 12 45 43" src="https://github.com/usefulness/easylauncher-gradle-plugin/assets/34095089/6d5c0c2d-e9a6-4a69-9450-0d441fae3b36">

**Comment by storytellerF** [comment]
We could add https://github.com/skyinu/j-webp for alternatives WEBPReaderSpi. @mateuszkwiecinski

**Comment by storytellerF** [comment]
add `--no-daemon` command paramater.

```shell
sh gradlew build --no-daemon
```

**Comment by Gfadebayo** [comment]
> add `--no-daemon` command paramater.
> 
> ```shell
> sh gradlew build --no-daemon
> ```

This worked for me
